system:
  port: "8182"
redis:
  host: "127.0.0.1:6379"
  password:
  timeout: 200
  #  最大活动连接数
  max_active: 30
  #  最大闲置连接
  max_idle: 30
postgres:
  host: "121.5.157.170"
  user: "postgres"
  password: "wwwpg88com"
  dbname: "postgres"
  port: "5432"